[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"


[project]
name = "chat657"
dynamic = ["version"]
authors = [
  { name="Oscar F" },
]
description = "A simple chat."
readme = "README.md"
license = "MIT"
license-files = [
  "LICENSE.md",
]
requires-python = ">= 3.12"
dependencies = [
    "django",
    "channels",
    "channels-redis",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
]

[project.urls]
repository = "https://github.com/oscfr657/chat657.git"

[tool.setuptools]
packages = ["chat657"]
package-dir = {'chat657' = '.'}

[tool.setuptools.package-data]
chat657 = [
  './migrations/*',
  './static/*/*/*',
  './static/*/*/*/*',
  './templates/*',
  './templates/*/*',
  ]

[tool.setuptools.dynamic]
version = {file = "VERSION.txt"}
