# Generated by Django 6.0.8 on 2026-08-10 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat657', '0002_alter_room_participants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='participants',
            field=models.ManyToManyField(related_name='joined_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
    ]
